# Generated by Django 6.0.6 on 2026-06-16 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apodo', models.CharField(blank=True, max_length=50)),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(default='Paraguay', max_length=100)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='integrantes/')),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Integrante',
                'verbose_name_plural': 'Integrantes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('raza', models.CharField(choices=[('pitbull', 'American Pit Bull Terrier'), ('bully', 'American Bully')], max_length=20)),
                ('variante', models.CharField(choices=[('na', 'N/A'), ('pocket', 'Pocket'), ('standard', 'Standard'), ('classic', 'Classic'), ('xl', 'XL'), ('extreme', 'Extreme')], default='na', max_length=20)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('color', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('procedencia', models.CharField(blank=True, help_text='De quién adquirió el perro', max_length=200)),
                ('tiene_registro', models.BooleanField(default=False)),
                ('numero_registro', models.CharField(blank=True, max_length=100)),
                ('kennel', models.CharField(blank=True, help_text='Nombre del kennel o asociación', max_length=100)),
                ('padre', models.CharField(blank=True, max_length=100)),
                ('madre', models.CharField(blank=True, max_length=100)),
                ('foto_principal', models.ImageField(blank=True, null=True, upload_to='perros/')),
                ('notas', models.TextField(blank=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perros', to='club.integrante')),
            ],
            options={
                'verbose_name': 'Perro',
                'verbose_name_plural': 'Perros',
                'ordering': ['nombre'],
            },
        ),
    ]
