# Generated by Django 6.0.6 on 2026-06-16 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Campeonato',
                'verbose_name_plural': 'Campeonatos',
                'ordering': ['-año'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('exposicion', 'Exposición'), ('competencia', 'Competencia'), ('seminario', 'Seminario'), ('reunion', 'Reunión'), ('capacitacion', 'Capacitación'), ('otro', 'Otro')], default='exposicion', max_length=20)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('lugar', models.CharField(max_length=200)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('organizador', models.CharField(blank=True, max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('inscripcion_abierta', models.BooleanField(default=True)),
                ('cupo', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('resumen', models.TextField(blank=True)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='noticias/')),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('publicada', models.BooleanField(default=True)),
                ('destacada', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.AddField(
            model_name='perro',
            name='altura',
            field=models.IntegerField(blank=True, help_text='Altura en cm al hombro', null=True),
        ),
        migrations.AddField(
            model_name='perro',
            name='criador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criados', to='club.integrante', verbose_name='Criador'),
        ),
        migrations.AddField(
            model_name='perro',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Mostrar en la página principal'),
        ),
        migrations.AddField(
            model_name='perro',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('retirado', 'Retirado'), ('fallecido', 'Fallecido')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='perro',
            name='microchip',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='perro',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kg', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='perro',
            name='dueno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perros', to='club.integrante', verbose_name='Dueño'),
        ),
        migrations.CreateModel(
            name='FotoPerro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='perros/galeria/')),
                ('es_principal', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
                ('perro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='club.perro')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PuntoCampeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(default=0)),
                ('posicion', models.IntegerField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='club.campeonato')),
                ('perro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_campeonato', to='club.perro')),
            ],
            options={
                'verbose_name': 'Punto de Campeonato',
                'verbose_name_plural': 'Puntos de Campeonato',
                'ordering': ['posicion', '-puntos'],
            },
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('organizacion', models.CharField(blank=True, max_length=100)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('perro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulos', to='club.perro')),
            ],
            options={
                'verbose_name': 'Título',
                'verbose_name_plural': 'Títulos',
                'ordering': ['-fecha'],
            },
        ),
    ]
