# Generated by Django 6.0.6 on 2026-06-19 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_campeonato_evento_noticia_perro_altura_perro_criador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrante',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='integrante',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='Camada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('padre_externo', models.CharField(blank=True, help_text='Nombre del padre si no es integrante del club', max_length=100)),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('cantidad_total', models.IntegerField(default=0, verbose_name='Total cachorros')),
                ('cantidad_machos', models.IntegerField(default=0, verbose_name='Machos')),
                ('cantidad_hembras', models.IntegerField(default=0, verbose_name='Hembras')),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('madre', models.ForeignKey(limit_choices_to={'sexo': 'H'}, on_delete=django.db.models.deletion.CASCADE, related_name='camadas_como_madre', to='club.perro', verbose_name='Madre')),
                ('padre', models.ForeignKey(blank=True, limit_choices_to={'sexo': 'M'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camadas_como_padre', to='club.perro', verbose_name='Padre (del club)')),
            ],
            options={
                'verbose_name': 'Camada',
                'verbose_name_plural': 'Camadas',
                'ordering': ['-fecha_nacimiento'],
            },
        ),
    ]
