# Generated by Django 6.0.6 on 2026-06-19 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_integrante_latitud_integrante_longitud_camada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='integrante',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Nro. Cédula'),
        ),
        migrations.AddField(
            model_name='integrante',
            name='debe_cambiar_password',
            field=models.BooleanField(default=True, verbose_name='Debe cambiar contraseña'),
        ),
        migrations.AddField(
            model_name='integrante',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrante', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del sistema'),
        ),
    ]
